---
# tasks file for aws_net

- name: Create an aws EC2 instance 
  amazon.aws.ec2_instance:
    name: "{{ name }}"
    image_id: "{{ image_id }}"
    instance_type: "{{ instance_type }}"
    key_name: "{{ key_name }}"
    region: "{{ region }}"
    user_data: "{{ lookup('template', '../templates/userdata.sh.j2') }}"
    security_group: "{{ security_group.group_id }}"
    vpc_subnet_id: "{{ public_subnet_out.results[0].subnet.id }}"
    tags: 
      Environment: "{{ env_name}}"
